@host=http://localhost:5005

POST {{host}}/auth/register
Content-Type: application/json

{
    "firstName": "Amichai",
    "lastName": "Mantinband",
    "email": "amichai@mantiband.com",
    "password": "Amiko1232!"
}